### PR TITLE
Added Swift Package Manager Support

### PR DESCRIPTION
**Pull request by mRs-**

### CODE REVIEW

**Comment by regexident** [comment]
This unfortunately needs some rebasing, now that PR 3 has been merged. (My apologies 😇 )

**Comment by frankrausch** [comment]
So … who does that rebasing? Can I do it?

**Comment by regexident** [comment]
@frankrausch: yes, you should have commit access to the PR, otherwise @mRs- would have to do it.

The PR moves the source files into `/Sources` as that's where SPM expects them to be.

**Comment by frankrausch** [comment]
@mRs- I’m having trouble pushing my merge to the PR. Would you please do the rebasing? Thanks.

**Comment by frankrausch** [comment]
@mRs- Nevermind, I am restructuring the Xcode project a bit and have already replicated your changes for SPM. Thanks.

**Pull request closed without merging**
