### PR TITLE
Add Carthage support, unit tests and a basic benchmark

### PR DESCRIPTION
**Pull request by regexident**
Hey Frank,

it was a pleasure getting to talk to you in person at UIKonf, not to mention watching your splendid talk!

I took the liberty to restructure the project a bit to allow for the addition of:

- [x] Carthage support (aka. a shared framework target)
- [x] Basic unit tests
- [x] Basic benchmarks

I hope the changes aren't too invasive for your taste.

\- Vincent

### CODE REVIEW

**Comment by mRs-** [comment]
Awesome work Vincent,

now I can start to tackle the cyclomatic complexety issue of `private mutating func fixableToken(_ first: UnicodeScalar) throws -> Token`.

@frankrausch as a next step it would be awesome to setup travis to run this unit tests everytime a new pull request is coming in.

**Comment by regexident** [comment]
Thanks Marius,

> now I can start to tackle the cyclomatic complexety issue of private mutating func fixableToken(_ first: UnicodeScalar) throws -> Token.

Awesome!

I have some optimizations for `TypographizerTokenResult` that I'll address next, as well as some possible cleanups for how language configs are stored internally, paving the way for possible future expansions.

**Comment by MattesGroeger** [comment]
@regexident Thanks for adding Carthage support! Please update the Readme as well (especially the install instructions).

**Comment by frankrausch** [comment]
Thanks, Vincent.
I’ll look into Travis support ASAP.

**Comment by regexident** [comment]
@MattesGroeger: see https://github.com/frankrausch/Typographizer/pull/2#issuecomment-302646483

I'd offer to write up a PR for the updated README later today, unless @frankrausch wants to tackle it himself.

**Comment by regexident** [comment]
> I’ll look into Travis support ASAP.

@frankrausch: [Integrating Travis CI with Swift project](http://szulctomasz.com/2015/06/29/integrating-travis-ci-with-swift-project.html) 🙂

**Comment by frankrausch** [comment]
@MattesGroeger @regexident Feel free to update the README, I’ll try to review everything over the weekend. Thanks!

**Comment by frankrausch** [comment]
@regexident Looks like these changes broke the TypographizerDemo project. Xcode complains about a missing `project.pbxproj` file. If I restore the missing file, the project is still broken. Do you know what went wrong?

**Comment by frankrausch** [comment]
@regexident Oh, I see what’s going on: You moved the demo project contents into the new framework project.
I think I’d rather have the whole demo as a separate project that imports the framework.
Don’t worry, I’ll take care of this as soon as I can.

**Comment by regexident** [comment]
> I think I’d rather have the whole demo as a separate project that imports the framework.
> Don’t worry, I’ll take care of this as soon as I can.

Sure, please feel free to change things to whatever makes it work for you.

I renamed the xcodeproj and moved a couple of things, as it would have been a bit awkward to have the Carthage target be found in `TypographizerDemo.xcodeproj`, not `Typographizer.xcodeproj`.

Just keep in mind that SPM expects source files to be found within `/Sources`. There might be a way to customize this though. I'm not to experienced with SPM.

**Pull request merged**
