### PR TITLE
Cleaned up a bit the code style

### PR DESCRIPTION
**Pull request by mRs-**
Hi Frank,

nice talk 👍!

I cleaned a bit up the code to be more swiftier ;)

### CODE REVIEW

**Comment by regexident** [comment]
I wouldn't consider removing `self.` making things swiftier. Quite the contrary.
It makes things error-prone when refactoring at some later point. It's easy to leave a stray shadowing local variable after a refactoring, which won't get caught. `self.` should actually be mandatory, imho. 🤷‍♂️

**Comment by frankrausch** [comment]
Thanks for your pull request, @mRs- !
I really appreciate it.

I will happily apply your changes to the unnecessarily prefixed Token struct and Result enum.

But I agree with @regexident; `self.` makes the code easier to understand and less error-prone, even though it does add clutter. I know most devs prefer skipping `self.` if it’s not required by the context, but I’d like to keep all explicit references to `self`.

**Comment by mRs-** [comment]
Booo! self is there to show an explicit behaviour for closure usage ;)

**Comment by regexident** [comment]
I care about a feature's pros and cons, not so much it's nominal intended purpose. :wink:

And the cons far outweigh the pros for implicit `self.`, imho.
There is not a single bug caused by adding `self.`, while quite a bunch caused by removing `self.`.

**Comment by frankrausch** [comment]
Maybe we should discuss spaces vs. tabs instead? 😛

I would argue that `self`’s existence—and its required usage to resolve ambiguity—is a good argument to use it for general clarity, too.

And I tend to prefer clarity over brevity. A quick web search reveals that I’m not alone. If [Nate Cook recommends](http://stackoverflow.com/questions/24215578/when-should-i-access-properties-with-self-in-swift#comment37392347_24215657) using `self` everywhere, I guess it’s a matter of taste and not a matter of proficiency (which I tend to double-check, not being a computer scientist and all 😉).

Soooo, what are we gonna do here? I do want to pull your beautiful other changes, dear @mRs- …

**Comment by mRs-** [comment]
Im going to remove the selfs and add a contribution guideline section in readme to remove this pitfall for the next dev 👏

Von meinem iPhone gesendet

**Comment by mRs-** [comment]
I made the changes 🥇

**Comment by frankrausch** [comment]
Awesome! Thanks. Merging.

**Pull request merged**
